# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvpM5ySkn6gp55vTNjzPlGRyUJfGv0_v
"""

score = input().split()
count = 0
for i in score:
  if int(i) < 60:
    count += 1
print("不及格人数:",count)

total = 0
for i in score:
  total += int(i)
avg = total / len(score)
print(f"平均為:{avg}")